function fullscreen(){var a=document.getElementsByTagName("a");for(var i=0;i<a.length;i++){if(a[i].className.match("noeffect")){}else{a[i].onclick=function(){window.location=this.getAttribute("href");return false}}}}

function start(){
  language();
  fullscreen();
  team_phrase();
  sliders();
  pokemonListData();

  $('#clickme_CP_Search').click(function() {
      document.getElementById("Output_CP_Search_2").selectionStart = 0
      document.getElementById("Output_CP_Search_2").selectionEnd = 9999
  });

  $('#clickme_PVP_Stats').click(function() {
      document.getElementById("Output_PVP_Stats_textarea").selectionStart = 0
      document.getElementById("Output_PVP_Stats_textarea").selectionEnd = 9999
  });

}

function ventanaemergente(id,id2) {

  window.scrollTo(0, 0);
  document.body.scrollTop = 0;
  document.getElementById(id).style.display = "block";

    document.getElementById(id2).style.display = "none";

    if (id == "informacion") {
      document.body.style.backgroundColor = "#2a6c79";
    }
    else if (id == "ocultar") {
      document.body.style.backgroundColor = "#24ccaa";

    }
}

function pokemonListData() {
  document.getElementById("pokemon").innerHTML = '<option value="Bulbasaur">' +
  '<option value="Ivysaur">' +
  '<option value="Venusaur">' +
  '<option value="Charmander">' +
  '<option value="Charmeleon">' +
  '<option value="Charizard">' +
  '<option value="Squirtle">' +
  '<option value="Wartortle">' +
  '<option value="Blastoise">' +
  '<option value="Caterpie">' +
  '<option value="Metapod">' +
  '<option value="Butterfree">' +
  '<option value="Weedle">' +
  '<option value="Kakuna">' +
  '<option value="Beedrill">' +
  '<option value="Pidgey">' +
  '<option value="Pidgeotto">' +
  '<option value="Pidgeot">' +
  '<option value="Rattata">' +
  '<option value="Raticate">' +
  '<option value="Rattata Alola">' +
  '<option value="Raticate Alola">' +
  '<option value="Spearow">' +
  '<option value="Fearow">' +
  '<option value="Ekans">' +
  '<option value="Arbok">' +
  '<option value="Pichu">' +
  '<option value="Pikachu">' +
  '<option value="Raichu">' +
  '<option value="Raichu Alola">' +
  '<option value="Sandshrew">' +
  '<option value="Sandslash">' +
  '<option value="Sandshrew Alola">' +
  '<option value="Sandslash Alola">' +
  '<option value="Nidoran♀">' +
  '<option value="Nidorina">' +
  '<option value="Nidoqueen">' +
  '<option value="Nidoran♂">' +
  '<option value="Nidorino">' +
  '<option value="Nidoking">' +
  '<option value="Cleffa">' +
  '<option value="Clefairy">' +
  '<option value="Clefable">' +
  '<option value="Vulpix">' +
  '<option value="Ninetales">' +
  '<option value="Vulpix Alola">' +
  '<option value="Ninetales Alola">' +
  '<option value="Igglybuff">' +
  '<option value="Jigglypuff">' +
  '<option value="Wigglytuff">' +
  '<option value="Zubat">' +
  '<option value="Golbat">' +
  '<option value="Crobat">' +
  '<option value="Oddish">' +
  '<option value="Gloom">' +
  '<option value="Vileplume">' +
  '<option value="Bellossom">' +
  '<option value="Paras">' +
  '<option value="Parasect">' +
  '<option value="Venonat">' +
  '<option value="Venomoth">' +
  '<option value="Diglett">' +
  '<option value="Dugtrio">' +
  '<option value="Diglett Alola">' +
  '<option value="Dugtrio Alola">' +
  '<option value="Meowth">' +
  '<option value="Persian">' +
  '<option value="Meowth Alola">' +
  '<option value="Persian Alola">' +
  '<option value="Psyduck">' +
  '<option value="Golduck">' +
  '<option value="Mankey">' +
  '<option value="Primeape">' +
  '<option value="Growlithe">' +
  '<option value="Arcanine">' +
  '<option value="Poliwag">' +
  '<option value="Poliwhirl">' +
  '<option value="Poliwrath">' +
  '<option value="Politoed">' +
  '<option value="Abra">' +
  '<option value="Kadabra">' +
  '<option value="Alakazam">' +
  '<option value="Machop">' +
  '<option value="Machoke">' +
  '<option value="Machamp">' +
  '<option value="Bellsprout">' +
  '<option value="Weepinbell">' +
  '<option value="Victreebel">' +
  '<option value="Tentacool">' +
  '<option value="Tentacruel">' +
  '<option value="Geodude">' +
  '<option value="Graveler">' +
  '<option value="Golem">' +
  '<option value="Geodude Alola">' +
  '<option value="Graveler Alola">' +
  '<option value="Golem Alola">' +
  '<option value="Ponyta">' +
  '<option value="Rapidash">' +
  '<option value="Slowpoke">' +
  '<option value="Slowbro">' +
  '<option value="Slowking">' +
  '<option value="Magnemite">' +
  '<option value="Magneton">' +
  '<option value="Magnezone">' +
  '<option value="Farfetch´d">' +
  '<option value="Doduo">' +
  '<option value="Dodrio">' +
  '<option value="Seel">' +
  '<option value="Dewgong">' +
  '<option value="Grimer">' +
  '<option value="Muk">' +
  '<option value="Grimer Alola">' +
  '<option value="Muk Alola">' +
  '<option value="Shellder">' +
  '<option value="Cloyster">' +
  '<option value="Gastly">' +
  '<option value="Haunter">' +
  '<option value="Gengar">' +
  '<option value="Onix">' +
  '<option value="Steelix">' +
  '<option value="Drowzee">' +
  '<option value="Hypno">' +
  '<option value="Krabby">' +
  '<option value="Kingler">' +
  '<option value="Voltorb">' +
  '<option value="Electrode">' +
  '<option value="Exeggcute">' +
  '<option value="Exeggutor">' +
  '<option value="Exeggutor Alola">' +
  '<option value="Cubone">' +
  '<option value="Marowak">' +
  '<option value="Marowak Alola">' +
  '<option value="Tyrogue">' +
  '<option value="Hitmonlee">' +
  '<option value="Hitmonchan">' +
  '<option value="Hitmontop">' +
  '<option value="Lickitung">' +
  '<option value="Lickilicky">' +
  '<option value="Koffing">' +
  '<option value="Weezing">' +
  '<option value="Rhyhorn">' +
  '<option value="Rhydon">' +
  '<option value="Rhyperior">' +
  '<option value="Happiny">' +
  '<option value="Chansey">' +
  '<option value="Blissey">' +
  '<option value="Tangela">' +
  '<option value="Tangrowth">' +
  '<option value="Kangaskhan">' +
  '<option value="Horsea">' +
  '<option value="Seadra">' +
  '<option value="Kingdra">' +
  '<option value="Goldeen">' +
  '<option value="Seaking">' +
  '<option value="Staryu">' +
  '<option value="Starmie">' +
  '<option value="Mime Jr.">' +
  '<option value="Mr. Mime">' +
  '<option value="Scyther">' +
  '<option value="Scizor">' +
  '<option value="Smoochum">' +
  '<option value="Jynx">' +
  '<option value="Elekid">' +
  '<option value="Electabuzz">' +
  '<option value="Electivire">' +
  '<option value="Magby">' +
  '<option value="Magmar">' +
  '<option value="Magmortar">' +
  '<option value="Pinsir">' +
  '<option value="Tauros">' +
  '<option value="Magikarp">' +
  '<option value="Gyarados">' +
  '<option value="Lapras">' +
  '<option value="Ditto">' +
  '<option value="Eevee">' +
  '<option value="Vaporeon">' +
  '<option value="Jolteon">' +
  '<option value="Flareon">' +
  '<option value="Espeon">' +
  '<option value="Umbreon">' +
  '<option value="Leafeon">' +
  '<option value="Glaceon">' +
  '<option value="Porygon">' +
  '<option value="Porygon2">' +
  '<option value="PorygonZ">' +
  '<option value="Omanyte">' +
  '<option value="Omastar">' +
  '<option value="Kabuto">' +
  '<option value="Kabutops">' +
  '<option value="Aerodactyl">' +
  '<option value="Munchlax">' +
  '<option value="Snorlax">' +
  '<option value="Articuno">' +
  '<option value="Zapdos">' +
  '<option value="Moltres">' +
  '<option value="Dratini">' +
  '<option value="Dragonair">' +
  '<option value="Dragonite">' +
  '<option value="Mewtwo">' +
  '<option value="Mew">' +
  '<option value="Chikorita">' +
  '<option value="Bayleef">' +
  '<option value="Meganium">' +
  '<option value="Cyndaquil">' +
  '<option value="Quilava">' +
  '<option value="Typhlosion">' +
  '<option value="Totodile">' +
  '<option value="Croconaw">' +
  '<option value="Feraligatr">' +
  '<option value="Sentret">' +
  '<option value="Furret">' +
  '<option value="Hoothoot">' +
  '<option value="Moctowl">' +
  '<option value="Ledyba">' +
  '<option value="Ledian">' +
  '<option value="Spinarak">' +
  '<option value="Ariados">' +
  '<option value="Chinchou">' +
  '<option value="Lanturn">' +
  '<option value="Togepi">' +
  '<option value="Togetic">' +
  '<option value="Togekiss">' +
  '<option value="Matu">' +
  '<option value="Xatu">' +
  '<option value="Mareep">' +
  '<option value="Flaaffy">' +
  '<option value="Ampharos">' +
  '<option value="Azurill">' +
  '<option value="Marill">' +
  '<option value="Azumarill">' +
  '<option value="Bonsly">' +
  '<option value="Sudowoodo">' +
  '<option value="Hoppip">' +
  '<option value="Skiploom">' +
  '<option value="Jumpluff">' +
  '<option value="Aipom">' +
  '<option value="Ambipom">' +
  '<option value="Sunkern">' +
  '<option value="Sunflora">' +
  '<option value="Yanma">' +
  '<option value="Yanmega">' +
  '<option value="Wooper">' +
  '<option value="Quagsire">' +
  '<option value="Murkrow">' +
  '<option value="Honchkrow">' +
  '<option value="Misdreavus">' +
  '<option value="Mismagius">' +
  '<option value="Unown">' +
  '<option value="Wynaut">' +
  '<option value="Wobbuffet">' +
  '<option value="Girafarig">' +
  '<option value="Pineco">' +
  '<option value="Forretress">' +
  '<option value="Dunsparce">' +
  '<option value="Gligar">' +
  '<option value="Gliscor">' +
  '<option value="Snubbull">' +
  '<option value="Granbull">' +
  '<option value="Qwilfish">' +
  '<option value="Shuckle">' +
  '<option value="Heracross">' +
  '<option value="Sneasel">' +
  '<option value="Weavile">' +
  '<option value="Teddiursa">' +
  '<option value="Ursaring">' +
  '<option value="Slugma">' +
  '<option value="Magcargo">' +
  '<option value="Swinub">' +
  '<option value="Piloswine">' +
  '<option value="Mamoswine">' +
  '<option value="Corsola">' +
  '<option value="Remoraid">' +
  '<option value="Octillery">' +
  '<option value="Delibird">' +
  '<option value="Mantine">' +
  '<option value="Skarmory">' +
  '<option value="Houndour">' +
  '<option value="Houndoom">' +
  '<option value="Phanpy">' +
  '<option value="Donphan">' +
  '<option value="Stantler">' +
  '<option value="Smeargle">' +
  '<option value="Miltank">' +
  '<option value="Raikou">' +
  '<option value="Entei">' +
  '<option value="Suicune">' +
  '<option value="Larvitar">' +
  '<option value="Pupitar">' +
  '<option value="Tyranitar">' +
  '<option value="Lugia">' +
  '<option value="Ho-Oh">' +
  '<option value="Celebi">' +
  '<option value="Treecko">' +
  '<option value="Grovyle">' +
  '<option value="Sceptile">' +
  '<option value="Torchic">' +
  '<option value="Combusken">' +
  '<option value="Blaziken">' +
  '<option value="Mudkip">' +
  '<option value="Marshtomp">' +
  '<option value="Swampert">' +
  '<option value="Poochyena">' +
  '<option value="Mightyena">' +
  '<option value="Zigzagoon">' +
  '<option value="Linoone">' +
  '<option value="Wurmple">' +
  '<option value="Silcoon">' +
  '<option value="Beautifly">' +
  '<option value="Cascoon">' +
  '<option value="Dustox">' +
  '<option value="Lotad">' +
  '<option value="Lombre">' +
  '<option value="Ludicolo">' +
  '<option value="Seedot">' +
  '<option value="Nuzleaf">' +
  '<option value="Shiftry">' +
  '<option value="Taillow">' +
  '<option value="Swellow">' +
  '<option value="Wingull">' +
  '<option value="Pelipper">' +
  '<option value="Ralts">' +
  '<option value="Kirlia">' +
  '<option value="Gardevoir">' +
  '<option value="Gallade">' +
  '<option value="Surskit">' +
  '<option value="Masquerain">' +
  '<option value="Shroomish">' +
  '<option value="Breloom">' +
  '<option value="Slakoth">' +
  '<option value="Vigoroth">' +
  '<option value="Slaking">' +
  '<option value="Nincada">' +
  '<option value="Ninjask">' +
  '<option value="Shedinja">' +
  '<option value="Whismur">' +
  '<option value="Loudred">' +
  '<option value="Exploud">' +
  '<option value="Makuhita">' +
  '<option value="Hariyama">' +
  '<option value="Nosepass">' +
  '<option value="Probopass">' +
  '<option value="Skitty">' +
  '<option value="Delcatty">' +
  '<option value="Sableye">' +
  '<option value="Mawile">' +
  '<option value="Aron">' +
  '<option value="Lairon">' +
  '<option value="Aggron">' +
  '<option value="Meditite">' +
  '<option value="Medicham">' +
  '<option value="Electrike">' +
  '<option value="Manectric">' +
  '<option value="Plusle">' +
  '<option value="Minun">' +
  '<option value="Volbeat">' +
  '<option value="Illumise">' +
  '<option value="Budew">' +
  '<option value="Roselia">' +
  '<option value="Roserade">' +
  '<option value="Gulpin">' +
  '<option value="Swalot">' +
  '<option value="Carvanha">' +
  '<option value="Sharpedo">' +
  '<option value="Wailmer">' +
  '<option value="Wailord">' +
  '<option value="Numel">' +
  '<option value="Camerupt">' +
  '<option value="Torkoal">' +
  '<option value="Spoink">' +
  '<option value="Grumpig">' +
  '<option value="Trapinch">' +
  '<option value="Vibrava">' +
  '<option value="Flygon">' +
  '<option value="Cacnea">' +
  '<option value="Cacturne">' +
  '<option value="Swablu">' +
  '<option value="Altaria">' +
  '<option value="Zangoose">' +
  '<option value="Seviper">' +
  '<option value="Lunatone">' +
  '<option value="Solrock">' +
  '<option value="Barboach">' +
  '<option value="Whiscash">' +
  '<option value="Corphish">' +
  '<option value="Crawdaunt">' +
  '<option value="Baltoy">' +
  '<option value="Claydol">' +
  '<option value="Lileep">' +
  '<option value="Cradily">' +
  '<option value="Anorith">' +
  '<option value="Armaldo">' +
  '<option value="Feebas">' +
  '<option value="Milotic">' +
  '<option value="Castform">' +
  '<option value="Shuppet">' +
  '<option value="Banette">' +
  '<option value="Duskull">' +
  '<option value="Dusclops">' +
  '<option value="Dusknoir">' +
  '<option value="Tropius">' +
  '<option value="Chimecho">' +
  '<option value="Chingling">' +
  '<option value="Absol">' +
  '<option value="Snorunt">' +
  '<option value="Glalie">' +
  '<option value="Spheal">' +
  '<option value="Sealeo">' +
  '<option value="Walrein">' +
  '<option value="Clamperl">' +
  '<option value="Huntail">' +
  '<option value="Gorebyss">' +
  '<option value="Relicanth">' +
  '<option value="Luvdisc">' +
  '<option value="Bagon">' +
  '<option value="Shelgon">' +
  '<option value="Salamence">' +
  '<option value="Beldum">' +
  '<option value="Metang">' +
  '<option value="Metagross">' +
  '<option value="Regirock">' +
  '<option value="Regice">' +
  '<option value="Registeel">' +
  '<option value="Latias">' +
  '<option value="Latios">' +
  '<option value="Kyogre">' +
  '<option value="Groudon">' +
  '<option value="Rayquaza">' +
  '<option value="Deoxys normal">' +
  '<option value="Deoxys attack">' +
  '<option value="Deoxys defense">' +
  '<option value="Deoxys speed">' +
  '<option value="Turtwig">' +
  '<option value="Grotle">' +
  '<option value="Torterra">' +
  '<option value="Chimchar">' +
  '<option value="Monferno">' +
  '<option value="Infernape">' +
  '<option value="Piplup">' +
  '<option value="Prinplup">' +
  '<option value="Empoleon">' +
  '<option value="Starly">' +
  '<option value="Staravia">' +
  '<option value="Staraptor">' +
  '<option value="Bidoof">' +
  '<option value="Bibarel">' +
  '<option value="Kricketot">' +
  '<option value="Kricketune">' +
  '<option value="Shinx">' +
  '<option value="Luxio">' +
  '<option value="Luxray">' +
  '<option value="Cranidos">' +
  '<option value="Rampardos">' +
  '<option value="Shieldon">' +
  '<option value="Bastiodon">' +
  '<option value="Burmy">' +
  '<option value="Wormadam">' +
  '<option value="Mothim">' +
  '<option value="Combee">' +
  '<option value="Vespiquen">' +
  '<option value="Pachirisu">' +
  '<option value="Buizel">' +
  '<option value="Floatzel">' +
  '<option value="Cherubi">' +
  '<option value="Cherrim">' +
  '<option value="Shellos">' +
  '<option value="Gastrodon">' +
  '<option value="Drifloon">' +
  '<option value="Drifblim">' +
  '<option value="Buneary">' +
  '<option value="Lopunny">' +
  '<option value="Glameow">' +
  '<option value="Purugly">' +
  '<option value="Stunky">' +
  '<option value="Skuntank">' +
  '<option value="Bronzor">' +
  '<option value="Bronzong">' +
  '<option value="Chatot">' +
  '<option value="Spiritomb">' +
  '<option value="Gible">' +
  '<option value="Gabite">' +
  '<option value="Garchomp">' +
  '<option value="Riolu">' +
  '<option value="Lucario">' +
  '<option value="Hippopotas">' +
  '<option value="Hippowdon">' +
  '<option value="Skorupi">' +
  '<option value="Drapion">' +
  '<option value="Croagunk">' +
  '<option value="Toxicroak">' +
  '<option value="Carnivine">' +
  '<option value="Finneon">' +
  '<option value="Lumineon">' +
  '<option value="Snover">' +
  '<option value="Abomasnow">' +
  '<option value="Rotom">' +
  '<option value="Uxie">' +
  '<option value="Mesprit">' +
  '<option value="Azelf">' +
  '<option value="Dialga">' +
  '<option value="Palkia">' +
  '<option value="Heatran">' +
  '<option value="Regigigas">' +
  '<option value="Giratina Altered">' +
  '<option value="Giratina Origin">' +
  '<option value="Cresselia">' +
  '<option value="Darkrai">' +
  '<option value="Arceus">' +
  '<option value="Meltan">' +
  '<option value="Melmetal">'
}